### PR TITLE
Python Bindings For Symspell-Rust

### PR DESCRIPTION
**Pull request by VJAYSLN**
Hello @reneklacan , Here, I Create a folder named bindings, there i added my python bindings for this package implemented by Pyo3. Please check and merge the same.

### CODE REVIEW

**Comment by reneklacan** [comment]
Hey @VJAYSLN, thank you very much for your contribution but I'm a bit on the fence about whether Python bindings should reside in this repository.

I think it might really negatively affect development as one would have to make sure to update python bindings every time there's some potentially breaking change which can discourage contributions from some people.

While in a separate repository, it wouldn't be a problem as you can rely on specific version of symspell crate.

@MRoci What do you think?

**Comment by reneklacan** [comment]
Closes https://github.com/reneklacan/symspell/issues/13

**Comment by VJAYSLN** [comment]
Solved on #16

**Comment by MRoci** [comment]
@VJAYSLN nice work! Just for info have you tried doing some benchmark compared to the pure python implementation ?
 
@reneklacan i agree with you that adding too many bindings in this repo could create some trouble during development. We have to transpose every update also to bindings as we have no way to leave them behind without breaking the whole thing.
(Also we risk to end up having files full of  `#cfg(target="this") #cfg(taget="that")` )

Maybe we should consider also to move out the JS bindings for coherence, but one thing that would be nice in order to have the same functionality is to expose string strategies as features (enabled by default), so we can turn it off as needed.

**Comment by VJAYSLN** [comment]
Thanks @MRoci , I've compared python binding vs pure python implementation.
Here listed some results which I got for pure python implementation and pyo3 implementation resp,

- Lookup _(Time in secs)_              **0.00021            0.000045**
- Lookup_Compound                **0.053            0.0049**

**Pull request closed without merging**
