### PR TITLE
Update to SymSpell v6.5

### PR DESCRIPTION
**Pull request by MRoci**
This PR aims improve `lookup_compound` function with algorithms from SymSpell v6.5.
It provides better correction quality by using Naive Bayes probability for selecting best word splitting.

It includes some unit tests from the original project to ensure accuracy.

The behaviour of `create_dictionary_entry` was modified in order to update existing words by sum (currently it overrides the entry) to match other implementations.

Also the `lookup` function was modified because it was calling `unidecode` with no regards of chosen `StringStrategy` causing accented letters to not be spellchecked correctly

In additon, this fixes documentation tests and some warnings, in order to have green light  when `cargo test` 

Bigram frequency dicitionaries support is still missing

### CODE REVIEW

**Comment by xrmx** [comment]
@reneklacan On our tests this updated rust implementation now matches in accuracy the symspellpy port where previously it was like half good. Would be nice to have a new released version after this has been merged.
Speaking of releases any chance you may want to care of pushing the webasm version to npm too? Thanks!

**Comment by reneklacan** [comment]
@MRoci @xrmx Thank you very much for your contributions! ❤️

> On our tests this updated rust implementation now matches in accuracy the symspellpy port where previously it was like half good.

Awesome

> Would be nice to have a new released version after this has been merged please.

Sure!

> Speaking of releases any chance you may want to care of pushing the webasm version to npm too? 

Sounds good!

**Comment by reneklacan** [comment]
@MRoci @xrmx 

Published as v0.2.0

- https://github.com/reneklacan/symspell/releases/tag/v0.2.0
- https://crates.io/crates/symspell/0.2.0

**Comment by xrmx** [comment]
@reneklacan thanks a lot!

**Comment by xrmx** [comment]
BTW if you can hook the repo to travis we'll have CI on pull requests for free: https://travis-ci.com/reneklacan/

**Comment by reneklacan** [comment]
@xrmx Done https://travis-ci.com/reneklacan/symspell but I generally prefer CircleCI or Github actions, Travis stopped innovating and it seems to be losing popularity and is slowly dying out. But it's ok for now, we can switch any time in the future.

**Pull request merged**
